<a href="https://colab.research.google.com/github/YoannRaguenes/Projet-Data-Science-Clubs-De-Foot-Anglais/blob/master/club.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd

In [0]:
def Creationdataframe(Url,nom_league):

  html = urlopen(Url)
  html_soup = BeautifulSoup(html, 'html.parser')
  rows = html_soup.findAll("div",class_="overthrow table_container")

  trs = rows[1].table.findAll("tr")
  trs[2].a.findAll("href")
  trs2 = rows[0].table.findAll("tr")
  trs2[1:][0].findAll("td",class_="right")[-1].text

  data=trs[2:][1].findAll("td",class_="right")
  l = trs[2:]
  m=trs2[1:]
  m[0].a

  nom_dataframe = []
  for row in range(len(l)):
      
      try:
          club4 = {
                  "name": l[row].a.text,
                   "league": nom_league,
                  "games_home": l[row].findAll("td",class_="right")[0].text,
                  "wins_home": l[row].findAll("td",class_="right")[1].text,
                  "draws_home": l[row].findAll("td",class_="right")[2].text,
                  "losses_home": l[row].findAll("td",class_="right")[3].text,
                  "goals_for_home": l[row].findAll("td",class_="right")[4].text,
                  "goals_against_home": l[row].findAll("td",class_="right")[5].text,
                  "goal_diff_home": l[row].findAll("td",class_="right")[6].text,
                  "points_home": l[row].findAll("td",class_="right")[7].text,
                  "points_avg_home": l[row].findAll("td",class_="right")[8].text,
                  "games_away": l[row].findAll("td",class_="right")[9].text,
                  "wins_away": l[row].findAll("td",class_="right")[10].text,
                  "draws_away": l[row].findAll("td",class_="right")[11].text,
                  "losses_away": l[row].findAll("td",class_="right")[12].text,
                  "goals_for_away": l[row].findAll("td",class_="right")[13].text,
                  "goals_against_away": l[row].findAll("td",class_="right")[14].text,
                  "goal_diff_away": l[row].findAll("td",class_="right")[15].text,
                  "points_away": l[row].findAll("td",class_="right")[16].text,
                  "points_avg_away": l[row].findAll("td",class_="right")[16].text,
                  "top_team_scorers":m[row].findAll("td",class_="right")[-2].text,
                  "top_keeper":m[row].findAll("td",class_="right")[-1].text
              
              }
          nom_dataframe.append(club4)
          
      except ValueError:
              print("Ouch!")

  dataframe = pd.DataFrame(nom_dataframe)
  

  return dataframe

In [0]:
df_national_league =Creationdataframe("https://fbref.com/en/comps/34/National-League-Stats","National League")

In [4]:
df_league_two = Creationdataframe("https://fbref.com/en/comps/16/League-Two-Stats","League Two")
df_league_two

               name  ...            top_keeper
0   Crewe Alexandra  ...  William Jääskeläinen
1      Swindon Town  ...          Steven Benda
2   Plymouth Argyle  ...           Alex Palmer
3       Exeter City  ...            Lewis Ward
4        Cheltenham  ...        Scott Flinders
5    Colchester Utd  ...           Dean Gerken
6       Northampton  ...         David Cornell
7         Port Vale  ...           Scott Brown
8     Bradford City  ...     Richard O'Donnell
9      Salford City  ...         Kyle Letheren
10        FG Rovers  ...          Lewis Thomas
11     Crawley Town  ...          Glenn Morris
12     Grimsby Town  ...         James McKeown
13          Walsall  ...          Liam Roberts
14   Newport County  ...              Tom King
15    Cambridge Utd  ...         Dimitar Mitov
16    Leyton Orient  ...            Dean Brill
17  Carlisle United  ...           Adam Collin
18  Oldham Athletic  ...        Zeus de la Paz
19   Scunthorpe Utd  ...           Rory Watson
20   Mansfield Town  ...          Conrad Logan
21     Macclesfield  ...            Owen Evans
22        Morecambe  ...           Barry Roche
23        Stevenage  ...           Paul Farman

[24 rows x 22 columns]

In [5]:
df_league_three = Creationdataframe("https://fbref.com/en/comps/15/League-One-Stats","League One")
df_league_three

               name  ...            top_keeper
0     Coventry City  ...          Marko Maroši
1     Rotherham Utd  ...        Daniel Iversen
2     Oxford United  ...        Simon Eastwood
3        Portsmouth  ...    Craig MacGillivray
4    Fleetwood Town  ...           Alex Cairns
5     P'borough Utd  ...           Christy Pym
6        Sunderland  ...        Jon McLaughlin
7           Wycombe  ...           Ryan Allsop
8         Doncaster  ...         Timothy Dieng
9      Ipswich Town  ...            Tomáš Holý
10       Gillingham  ...           Jack Bonham
11    Burton Albion  ...         Kieran O'Hara
12        Blackpool  ...           Jak Alnwick
13   Bristol Rovers  ...        Anssi Jaakkola
14     Lincoln City  ...          Josh Vickers
15       Shrewsbury  ...           Max O'Leary
16  Acc'ton Stanley  ...       Dimitar Evtimov
17          MK Dons  ...          Lee Nicholls
18         Rochdale  ...  Robert Lynch Sanchez
19    AFC Wimbledon  ...          Nathan Trott
20  Tranmere Rovers  ...          Scott Davies
21  Southend United  ...            Mark Oxley
22           Bolton  ...         Remi Matthews
23             Bury  ...

[24 rows x 22 columns]

In [0]:
df_chamionship = Creationdataframe("https://fbref.com/en/comps/10/Championship-Stats","Championship")
df_chamionship

we're collecting data for first league players.

In [0]:

Url = "https://fbref.com/en/comps/9/Premier-League-Stats"
nom_league ="Premier League"

html = urlopen(Url)
html_soup = BeautifulSoup(html, 'html.parser')
rows = html_soup.findAll("div",class_="overthrow table_container")

trs = rows[1].table.findAll("tr")
trs[2].a.findAll("href")
trs2 = rows[0].table.findAll("tr")
trs2[1:][0].findAll("td",class_="right")[-1].text

data=trs[2:][1].findAll("td",class_="right")
l = trs[2:]
m=trs2[1:]
m[0].a

nom_dataframe = []
for row in range(len(l)):
    
    try:
        club4 = {
                "name": l[row].a.text,
                  "league": nom_league,
                "games_home": l[row].findAll("td",class_="right")[0].text,
                "wins_home": l[row].findAll("td",class_="right")[1].text,
                "draws_home": l[row].findAll("td",class_="right")[2].text,
                "losses_home": l[row].findAll("td",class_="right")[3].text,
                "goals_for_home": l[row].findAll("td",class_="right")[4].text,
                "goals_against_home": l[row].findAll("td",class_="right")[5].text,
                "goal_diff_home": l[row].findAll("td",class_="right")[6].text,
                "points_home": l[row].findAll("td",class_="right")[7].text,
                "points_avg_home": l[row].findAll("td",class_="right")[8].text,
                "games_away": l[row].findAll("td",class_="right")[13].text,
                "wins_away": l[row].findAll("td",class_="right")[14].text,
                "draws_away": l[row].findAll("td",class_="right")[15].text,
                "losses_away": l[row].findAll("td",class_="right")[16].text,
                "goals_for_away": l[row].findAll("td",class_="right")[17].text,
                "goals_against_away": l[row].findAll("td",class_="right")[18].text,
                "goal_diff_away": l[row].findAll("td",class_="right")[19].text,
                "points_away": l[row].findAll("td",class_="right")[20].text,
                "points_avg_away": l[row].findAll("td",class_="right")[21].text,
                "top_team_scorers":m[row].findAll("td",class_="right")[-2].text,
                "top_keeper":m[row].findAll("td",class_="right")[-1].text
            
            }
        nom_dataframe.append(club4)
        
    except ValueError:
            print("Ouch!")

dataframe1 = pd.DataFrame(nom_dataframe)

dataframe1

we concatenate all the dataframe to build a dataframe abd a csv file with all the english squad

In [0]:
df = pd.concat([df_national_league, df_league_two,df_league_three,df_chamionship,dataframe1])

In [0]:
df.to_csv("EnglishClubsStats.csv")