<a href="https://colab.research.google.com/github/YoannRaguenes/Projet-Data-Science-Clubs-De-Foot-Anglais/blob/master/club.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd

In [0]:
def Creationdataframe(Url,nom_league):

  html = urlopen(Url)
  html_soup = BeautifulSoup(html, 'html.parser')
  rows = html_soup.findAll("div",class_="overthrow table_container")

  trs = rows[1].table.findAll("tr")
  trs[2].a.findAll("href")
  trs2 = rows[0].table.findAll("tr")
  trs2[1:][0].findAll("td",class_="right")[-1].text

  data=trs[2:][1].findAll("td",class_="right")
  l = trs[2:]
  m=trs2[1:]
  m[0].a

  nom_dataframe = []
  for row in range(len(l)):
      
      try:
          club4 = {
                  "name": l[row].a.text,
                   "league": nom_league,
                  "games_home": l[row].findAll("td",class_="right")[0].text,
                  "wins_home": l[row].findAll("td",class_="right")[1].text,
                  "draws_home": l[row].findAll("td",class_="right")[2].text,
                  "losses_home": l[row].findAll("td",class_="right")[3].text,
                  "goals_for_home": l[row].findAll("td",class_="right")[4].text,
                  "goals_against_home": l[row].findAll("td",class_="right")[5].text,
                  "goal_diff_home": l[row].findAll("td",class_="right")[6].text,
                  "points_home": l[row].findAll("td",class_="right")[7].text,
                  "points_avg_home": l[row].findAll("td",class_="right")[8].text,
                  "games_away": l[row].findAll("td",class_="right")[9].text,
                  "wins_away": l[row].findAll("td",class_="right")[10].text,
                  "draws_away": l[row].findAll("td",class_="right")[11].text,
                  "losses_away": l[row].findAll("td",class_="right")[12].text,
                  "goals_for_away": l[row].findAll("td",class_="right")[13].text,
                  "goals_against_away": l[row].findAll("td",class_="right")[14].text,
                  "goal_diff_away": l[row].findAll("td",class_="right")[15].text,
                  "points_away": l[row].findAll("td",class_="right")[16].text,
                  "points_avg_away": l[row].findAll("td",class_="right")[16].text,
                  "top_team_scorers":m[row].findAll("td",class_="right")[-2].text,
                  "top_keeper":m[row].findAll("td",class_="right")[-1].text
              
              }
          nom_dataframe.append(club4)
          
      except ValueError:
              print("Ouch!")

  dataframe = pd.DataFrame(nom_dataframe)
  

  return dataframe

In [0]:
df_national_league =Creationdataframe("https://fbref.com/en/comps/34/National-League-Stats","National League")

In [0]:
df_league_two = Creationdataframe("https://fbref.com/en/comps/16/League-Two-Stats","League Two")

In [0]:
df_league_three = Creationdataframe("https://fbref.com/en/comps/15/League-One-Stats","League One")

In [0]:
df_chamionship = Creationdataframe("https://fbref.com/en/comps/10/Championship-Stats","Championship")

we're collecting data for first league players.

In [17]:

Url = "https://fbref.com/en/comps/9/Premier-League-Stats"
nom_league ="Premier League"

html = urlopen(Url)
html_soup = BeautifulSoup(html, 'html.parser')
rows = html_soup.findAll("div",class_="overthrow table_container")

trs = rows[1].table.findAll("tr")
trs[2].a.findAll("href")
trs2 = rows[0].table.findAll("tr")
trs2[1:][0].findAll("td",class_="right")[-1].text

data=trs[2:][1].findAll("td",class_="right")
l = trs[2:]
m=trs2[1:]
m[0].a

nom_dataframe = []
for row in range(len(l)):
    
    try:
        club4 = {
                "name": l[row].a.text,
                  "league": nom_league,
                "games_home": l[row].findAll("td",class_="right")[0].text,
                "wins_home": l[row].findAll("td",class_="right")[1].text,
                "draws_home": l[row].findAll("td",class_="right")[2].text,
                "losses_home": l[row].findAll("td",class_="right")[3].text,
                "goals_for_home": l[row].findAll("td",class_="right")[4].text,
                "goals_against_home": l[row].findAll("td",class_="right")[5].text,
                "goal_diff_home": l[row].findAll("td",class_="right")[6].text,
                "points_home": l[row].findAll("td",class_="right")[7].text,
                "points_avg_home": l[row].findAll("td",class_="right")[8].text,
                "games_away": l[row].findAll("td",class_="right")[13].text,
                "wins_away": l[row].findAll("td",class_="right")[14].text,
                "draws_away": l[row].findAll("td",class_="right")[15].text,
                "losses_away": l[row].findAll("td",class_="right")[16].text,
                "goals_for_away": l[row].findAll("td",class_="right")[17].text,
                "goals_against_away": l[row].findAll("td",class_="right")[18].text,
                "goal_diff_away": l[row].findAll("td",class_="right")[19].text,
                "points_away": l[row].findAll("td",class_="right")[20].text,
                "points_avg_away": l[row].findAll("td",class_="right")[21].text,
                "top_team_scorers":m[row].findAll("td",class_="right")[-2].text,
                "top_keeper":m[row].findAll("td",class_="right")[-1].text
            
            }
        nom_dataframe.append(club4)
        
    except ValueError:
            print("Ouch!")

dataframe1 = pd.DataFrame(nom_dataframe)

dataframe1

               name  ...         top_keeper
0         Liverpool  ...            Alisson
1   Manchester City  ...            Ederson
2    Leicester City  ...  Kasper Schmeichel
3           Chelsea  ...  Kepa Arrizabalaga
4    Manchester Utd  ...       David de Gea
5            Wolves  ...       Rui Patrício
6     Sheffield Utd  ...     Dean Henderson
7         Tottenham  ...    Paulo Gazzaniga
8           Arsenal  ...         Bernd Leno
9           Burnley  ...          Nick Pope
10   Crystal Palace  ...     Vicente Guaita
11          Everton  ...    Jordan Pickford
12    Newcastle Utd  ...    Martin Dúbravka
13      Southampton  ...      Alex McCarthy
14         Brighton  ...        Mathew Ryan
15         West Ham  ...   Łukasz Fabiański
16          Watford  ...         Ben Foster
17      Bournemouth  ...     Aaron Ramsdale
18      Aston Villa  ...         Tom Heaton
19     Norwich City  ...           Tim Krul

[20 rows x 22 columns]

we concatenate all the dataframe to build a dataframe abd a csv file with all the english squad

In [18]:
df = pd.concat([df_national_league, df_league_two,df_league_three,df_chamionship,dataframe1])
df

            name           league  ...        top_team_scorers        top_keeper
0         Barrow  National League  ...      Scott Quigley - 20        Joel Dixon
1      Harrogate  National League  ...       Jack Muldoon - 13     James Belshaw
2   Notts County  National League  ...       Kyle Wootton - 13      Sam Slocombe
3    Yeovil Town  National League  ...        Rhys Murphy - 17     Stuart Nelson
4   Boreham Wood  National League  ...  Kabongo Tshimanga - 18    Nathan Ashmore
..           ...              ...  ...                     ...               ...
15      West Ham   Premier League  ...    Sébastien Haller - 7  Łukasz Fabiański
16       Watford   Premier League  ...         Troy Deeney - 6        Ben Foster
17   Bournemouth   Premier League  ...       Callum Wilson - 8    Aaron Ramsdale
18   Aston Villa   Premier League  ...       Jack Grealish - 7        Tom Heaton
19  Norwich City   Premier League  ...        Teemu Pukki - 11          Tim Krul

[116 rows x 22 columns]